version: '3.8'

services:
  hosting-center:
    build:
      context: .
      dockerfile: hosting-center.Dockerfile
    container_name: hosting_center
    privileged: true
    dns:
      - 127.0.0.1
    cap_add:
      - SETUID
      - SETGID
      - NET_BIND_SERVICE
      - SETPCAP
    restart: always
    volumes:
      - ./data/ftp:/var/ftp
      - ./data/users:/var/www/users
      - ./ftp-config/proftpd.conf:/etc/proftpd/proftpd.conf
    ports:
      - '80:80'
      - '21:21'
      - '53:53/udp'
      - '3000:3000'
      - '5000:5000'
      - '30000-30009:30000-30009'
      - '20:20'
    environment:
      FTP_USER: admin
      FTP_PASS: admin

  database:
    image: postgres:latest
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_DB: hosting_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  pgdata:

